server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, ecommerce-api-gateway
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: ${CART_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/carts/**
        - id: order-service
          uri: ${ORDER_SERVICE_URI:http://localhost:8084}
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URI:http://localhost:8085}
          predicates:
            - Path=/inventory/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URI:http://localhost:8086}
          predicates:
            - Path=/payments/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI:http://localhost:8087}
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
